version: '3'
services:
  my-decaf-life-site:
    image: registry.digitalocean.com/natimate-container-registry/my-decaf-life-site:$SERVER_VERSION
    restart: always
    networks:
      src_nginx_and_certbot:
        ipv4_address: '10.56.1.70'
    volumes:
      - ./drizzle:/app/drizzle
      - ./logs:/app/logs
networks:
  src_nginx_and_certbot:
    external: true
